### DISCUSSION TITLE
Macvlan network driver in docker

### DISCUSSION THREAD

**Discussion by moltasbengtsson** [MDeLuise/plant-it#463] [General]
Has anyone been able to get Plant-it working with the containers using macvlan network?

When I configure the containers to use a macvlan network with static IP-addresses I cant get it to function properly.

You can reach the server at 10.0.35.33:3000, enter the 10.0.35.33:8080 and continue to the next step where you create an account (or log in if youve already created an account). It accepts the login credentials but it will either send you back to the first step (enter server url) with an "Ops! Cannot connect to the server"-error or it will actually take you to the start page.

![image](https://github.com/user-attachments/assets/f9c12798-b75e-47f1-bf93-8b388aa0c898)

There is obviously a connection between the web server and the database, since you can create an account and it accepts these credentials.

Theres no log entries from the docker containers regarding the login attempts or the "Cannot connect to the server"-error messages from what I can find.

docker-compose.yml:
```
networks:
  docker-net:
    external: true

name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: server.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
    ports:
      - "8080:8080"
      - "3000:3000"
    networks:
      docker-net:
        ipv4_address: 10.0.35.33

  db:
    image: mysql:8.0
    restart: always
    env_file: server.env
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      docker-net:
        ipv4_address: 10.0.35.34

  cache:
    image: redis:7.2.1
    restart: always
````

server.env:
```
#
# DB
#
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_DATABASE=bootdb
MYSQL_ROOT_PASSWORD=root

#
# JWT
#
JWT_SECRET=putTheSecretHere
JWT_EXP=1

#
# Server config
#
USERS_LIMIT=-1
UPLOAD_DIR=/upload-dir
API_PORT=8080
FLORACODEX_KEY=
LOG_LEVEL=DEBUG
ALLOWED_ORIGINS=*

#
# Cache
#
CACHE_TYPE=none
CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379
```

![image](https://github.com/user-attachments/assets/142174a0-1efe-4adf-afcb-09bf2467bac2)
