### DISCUSSION TITLE
Can't connect to the backend

### DISCUSSION THREAD

**Discussion by GerardPolloRebozado** [MDeLuise/plant-it#474] [Q&A]
Im trying to setup plant-it but when I open the url it ask me for the backend url I type my server ip and port of the backend but it gives error, I changed the ports as they are being used for other services following this [guide](https://docs.plant-it.org/0.9.0/server-installation/#change-ports-binding)

docker-compose.yml
```
name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: .env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - ./upload-dir:/upload-dir
    ports:
      - 8089:8080
      - 3010:3000
  db:
    image: mysql:8.0
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
  cache:
    image: redis:7.2.1
    restart: unless-stopped
networks: {}
```
.env
```
#
# DB
#
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_DATABASE=bootdb
MYSQL_ROOT_PASSWORD=root

#
# JWT
#
JWT_SECRET=[REDACTED]
JWT_EXP=1

#
# Server config
#
USERS_LIMIT=-1 # less then 0 means no limit
UPLOAD_DIR=/upload-dir # path to the directory used to store uploaded images, if on docker deployment leave as it is and change the volume binding in the docker-compose file if needed
API_PORT=8080
FLORACODEX_URL=https://api.floracodex.com
FLORACODEX_KEY=[REDACTED]
ALLOWED_ORIGINS=* # CORS allowed origins (comma separated list)
LOG_LEVEL=DEBUG # could be: DEBUG, INFO, WARN, ERROR
CONTACT_MAIL=[REDACTED]
REMINDER_NOTIFY_CHECK=0 30 7 * * * # 6-values crontab expression to set the check time for reminders
MAX_REQUESTS_PER_MINUTE=100 # rate limiting of the upcoming requests

#
# Notification
#
NTFY_ENABLED=true # if "false" ntfy service won't be available as notification dispatcher
GOTIFY_ENABLED=true # if "false" ntfy service won't be available as notification dispatcher

#
# Cache
#
CACHE_TYPE=redis # Cache type. By default, it's "redis" but can also be "none"
CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

#
# SMTP
#
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_EMAIL=[REDACTED]
SMTP_PASSWORD=[REDACTED]
SMTP_AUTH=true
SMTP_START_TTL=true
```
