### DISCUSSION TITLE
Using a custom domain with plant-it

### DISCUSSION THREAD

**Discussion by cbarond** [MDeLuise/plant-it#96] [Q&A] [answered]
Hello,

I'm having some issues getting plant-it to work with a Cloudflare tunnel. I'm doing this so that I can access the app from outside my network. When I run it locally, I have no issues. (I have the frontend port configured correctly.

My configuration (using placeholder names):
Cloudflare:
- plants.domain.com -> server-ip:4040
- plantsapi.domain.com/api -> server-ip:8080/api
frontend.env: 
- API_URL=http://plantsapi.domain.com/api

When I launch from plants.domain.com, it can't reach the page.
If I go by IP with the api address set in the .env, I get a network error.

Any guidance would be appreciated. 
Thank you!

**Comment by MDeLuise** [comment]
Hi @cbarond, thanks for opening the issue!
I'm not very familiar with Cloudflare tunneling, but let's try to fix this.

If I understand correctly, you're facing connectivity issues outside your network for both the frontend and backend, is that correct?

It seems odd that you're unable to connect to the frontend, as there shouldn't be any access restrictions. Unlike the backend, which has the `ALLOWED_ORIGINS` property filter.

As a quick test, could you try accessing the authentication page directly at `plants.domain.com/auth`? Can you connect to that page or you receive the same error as before?

**Reply by cbarond** [reply]
I am currently out of town, but I will check when I get back home. (Should be Friday or Saturday)

**Reply by MDeLuise** [reply]
Ok, perfect! I'll keep thinking about potential sources for the problem in the meantime.

**Reply by cbarond** [reply]
If I connect to the site itself when I'm already logged in, I get this error:
![image](https://github.com/MDeLuise/plant-it/assets/78887193/1f7135cf-cb91-458d-b1a9-dd5009a3c18c)
If I go to the auth page, I get this one:
![image](https://github.com/MDeLuise/plant-it/assets/78887193/35a61c8c-c16f-445f-a3fd-d08646b887e0)

The way the tunnel works is that the Cloudflare servers are connected to my server at home. I can connect subdomains to specific IP addresses and ports. Then, when that subdomain is accessed the traffic is securely routed into my network and to the specific IP.

Here is how I have it configured:
![image](https://github.com/MDeLuise/plant-it/assets/78887193/c8cb00ad-a8bd-4687-8d34-1512da5089c9)
![image](https://github.com/MDeLuise/plant-it/assets/78887193/edc3fa37-df98-45bc-883a-0f207cd980e3)

After doing some testing, I did find that `plantsapi.domain.com/api/swagger-ui/index.html` does seem to work properly.

**Reply by MDeLuise** [reply]
Thank you for reaching out and providing additional details. It appears that there may be an issue with the connection to the backend service. While it's strange that you can access `plantsapi.domain.com/api/swagger-ui/index.html` directly but encounter difficulties from the frontend, we can troubleshoot further to identify the root cause.

Regarding the Cloudflare mapping, it's possible that the current mapping configuration might be causing the issue. From what I understand, `plantsapi.domain.com/api/` is currently mapped to `http://server-ip:8080`, and the frontend is attempting to connect to `API_URL` value (i.e., `http://plantsapi.domain.com/api`). It's worth noting that this should be mapped to `http://server-ip:8080/api`. Therefore, I suggest adjusting the mapping to `http://plantsapi.domain.com/api` -> `http://server-ip:8080/api` (ensuring that the trailing `/api` is included).

If this does not change anything. Here are some questions to help gather more information:
1. Have you checked the browser console for any error messages when attempting to log in?
2. Could you inspect the network tab in your browser's developer tools while attempting to log in? Any requests made to the backend (such as to `info/ping`) might contain useful data for debugging purposes.
3. When you execute the following curl command: `curl -iX 'GET' 'plantsapi.domain.com/api/info/ping' -H 'accept: */*'` do you receive any response?

**Reply by cbarond** [reply]
The tunnel automatically forwards the path to the URL. It pretty much just replaces the domain with the ip:port.
I checked the network tab and it is trying to ping `plants.domain.com/api/info/ping`. However, my `frontend.env` is configured like this: 
![image](https://github.com/MDeLuise/plant-it/assets/78887193/a317e9b8-8a22-491a-ab44-5ca207e0b6ca)
The service seems to assume that the frontend and backend are under the same domain.

I set up a redirect to forward requests for `plants.domain.com/api` to `plantsapi.domain.com/api`. This works manually, but the auth page ping still doesn't work.

**Reply by MDeLuise** [reply]
I attempted to reproduce the issue locally using a configuration similar to yours, but I couldn't encounter the problem. Here's the setup I used, which seems comparable to yours, particularly for the `API_URL` value and `ALLOWED_ORIGINS`, tell me if it's not:
`docker-compose.yml`
```yml
version: "3"
name: plant-it
services:
    backend:
        image: msdeluise/plant-it-backend:latest
        env_file: backend.env
        depends_on:
          - db
          - cache
        restart: unless-stopped
        volumes:
          - "./upload-dir:/upload-dir"
        ports:
          - "8080:8080"

    db:
        image: mysql:8.0
        restart: always
        env_file: backend.env
        volumes:
          - "./db:/var/lib/mysql"

    cache:
        image: redis:7.2.1
        restart: always

    frontend:
        image: msdeluise/plant-it-frontend:latest
        env_file: frontend.env
        links:
          - backend
        ports:
          - "3000:3000"
```
`frontend.env`:
```properties
PORT=3000
API_URL=http://plantsapi.domain.com/api
WAIT_TIMEOUT=10000
CACHE_TTL_DAYS=7
BROWSER=none
```
`backend.env`:
```properties
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=bootdb
JWT_SECRET=putTheSecretHere
JWT_EXP=1
USERS_LIMIT=-1
UPLOAD_DIR=/upload-dir
API_PORT=8080
CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379
TREFLE_KEY=
ALLOWED_ORIGINS=*
LOG_LEVEL=DEBUG
UPDATE_EXISTING=false
```
When accessing the `/auth` page, the console indeed shows a request to `http://plantsapi.domain.com/api/info/ping` (obviously failing since I have no accesso to that endpoint), which is the correct endpoint specified in the `frontend.env` file. However, in your case, it seems that the frontend is attempting to ping `plants.domain.com/api/info/ping` instead of `http://plantsapi.domain.com/api/info/ping`, is that correct?

**Reply by cbarond** [reply]
I was able to get it to ping `http://plantsapi.domain.com/api/info/ping`. I changed it to the IP, recreated the container, changed it back to the URL, and recreated it again. However, I noticed that even with it set to the IP, it was not able to reach the backend.
![plant-it_ping](https://github.com/MDeLuise/plant-it/assets/78887193/2b7cb1d2-e1d1-46c7-a8d1-1e9cb4f12700)
The Response tab says this: `Failed to load response data: No data found for resources with given identifier`

After some more testing, with the IP set as the `API_URL`, accessing the service by IP works without issue. However, accessing it by domain fails at the ping, as in the picture above. It seems like it should work in this configuration since I am on the same network.

My config seems correct:
`docker-compose.yml`: I only changed the port and made the frontend restart automatically
```yml
version: "3"

name: plant-it
services:
  backend:
    image: msdeluise/plant-it-backend:latest
    env_file: backend.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    restart: always
    env_file: backend.env
    volumes:
      - "./db:/var/lib/mysql"

  cache:
    image: redis:7.2.1
    restart: always

  frontend:
    image: msdeluise/plant-it-frontend:latest
    restart: unless-stopped
    env_file: frontend.env
    links:
      - backend
    ports:
      - "4040:3000"
```
`frontend.env`: Currently set to use the IP
```dotenv
PORT=3000
API_URL=http://server-ip/api
WAIT_TIMEOUT=5000

PAGE_SIZE=25

BROWSER=none
```
`backend.env`:
```dotenv
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=bootdb

JWT_SECRET=secretHere
JWT_EXP=1

USERS_LIMIT=-1 # less then 0 means no limit
UPLOAD_DIR=/upload-dir
API_PORT=8080

CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

TRAFLE_KEY=trefleKeyHere

ALLOWED_ORIGINS=* 
```

I'm pretty sure it is not an issue with Cloudflare because I have 4 other services running with the same setup and they work fine. I could be wrong, though.
