### ISSUE TITLE
Backend always starts tomcat as https

### ISSUE THREAD

**Issue by Samurai1201** [MDeLuise/plant-it#132]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

The backend server always starts up tomcat in an https mode. When using http mode, the client always reports that the backend can not be reached. 
I can reach both the frontend and backend when browsing to them individually, but when using http to connect to the backend server it displays a warning, that this connection is tls only.
I also tried the ssl_enabled=true mode, but it causes some issues in browsers that i cant tolerate.

### Expected behaviour

The tomcat server is expected to run in an not https mode when setting the env varibale to ssl_enabled=false

### Steps to reproduce

I just used the default example from the documentation and modified the paths and ports according to documentation.

### Local environment

1. Docker
2. Compose.yaml:
```
version: "3"
name: plant-it
services:
  backend:
    image: msdeluise/plant-it-backend:latest
    env_file: backend.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "/pool/config/plantit/upload-dir:/upload-dir"
      - "/pool/config/plantit/certs:/certificates"
    ports:
      - "8089:8080"
  db:
    image: mysql:8.0
    restart: always
    env_file: backend.env
    volumes:
      - "/pool/config/plantit/db:/var/lib/mysql"
  cache:
    image: redis:7.2.1
    restart: always
  frontend:
    image: msdeluise/plant-it-frontend:latest
    env_file: frontend.env
    links:
      - backend
    ports:
      - "3009:3000"
    volumes:
      - "/pool/config/plantit/certs:/certificates"
```
3. Backend.env
```
#
# DB
#
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=bootdb

#
# JWT
#
JWT_SECRET=mfijekdkmvsfeqlkmqko51421551
JWT_EXP=1

#
# Server config
#
USERS_LIMIT=2
UPLOAD_DIR=/upload-dir
API_PORT=8080
TRAFLE_KEY=
ALLOWED_ORIGINS=*

#
# Cache
#
CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

#
# SSL
#
SSL_ENABLED=false
CERTIFICATE_PATH=/certificates/

```
4. Frontend.env
```
PORT=3000
API_URL=http://192.168.1.103:8089/api
WAIT_TIMEOUT=5000
PAGE_SIZE=25
BROWSER=none
SSL_ENABLED=false
CERTIFICATE_PATH=/certificates/
```

### Additional info

Thanks for your work on this cool project.
Hope you can help, would be amazing to use your app!
