### ISSUE TITLE
405 error 

### ISSUE THREAD

**Issue by Szymok** [MDeLuise/plant-it#138]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

After deploying the plant-it app on a Raspberry Pi using Portainer and Ubuntu, I encounter a 405 error when attempting to create an account or log in. The error message is displayed in a popup with an empty message body.

![image](https://github.com/MDeLuise/plant-it/assets/37596854/fd58cfda-e393-434e-a29b-b4e97368442c)

```
version: "3"
name: plant-it
services:
  backend:
    image: msdeluise/plant-it-backend:latest
    env_file: stack.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
      - "./certificates:/certificates"
    ports:
      - "9092:8080"

  db:
    image: mysql:8.0
    restart: always
    env_file: stack.env
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3307:3306"

  cache:
    image: redis:7.2.1
    restart: always

  frontend:
    image: msdeluise/plant-it-frontend:latest
    env_file: stack.env
    links:
      - backend
    ports:
      - "3090:3000"
    volumes:
      - "./certificates:/certificates"
volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certificates
```

### Expected behaviour

I would expect the account creation or login process to complete successfully without any errors, allowing me to access the plant-it app's features.

### Steps to reproduce

Deploy the plant-it app using the provided docker-compose file on a Raspberry Pi with Portainer and Ubuntu.
Navigate to the frontend service on port 3090.
Attempt to create a new account or log in with existing credentials.
Observe the 405 error in a popup window.

### Local environment

Raspberry Pi model: 4B
Ubuntu version: 22.01
Portainer version: 2.19.4
Browser and version: Edge v122.0.2365.92

### Additional info

The docker-compose file has been configured to expose the backend service on port 9092 and the frontend on port 3090.
The database service is exposed on port 3307.
The error occurs when the frontend service makes a POST request to the /api/authentication/signup endpoint.
Screenshot of the error is attached (attach the screenshot you provided).
