### ISSUE TITLE
Unable to access the server on v0.5.0

### ISSUE THREAD

**Issue by cbarond** [MDeLuise/plant-it#153]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

I just updated to version 0.5.0 and made sure to follow the steps outlined on the release page. However, I am unable to access the server. When I put in the server ip and port in the frontend, it says it can't connect to the server. Additionally, when I try to curl the `/api/info/ping` page from the host, I get the following errors:
- `localhost:8080`: `curl: (56) Recv failure: Connection reset by peer`
- `server-ip:8080`: `curl: (7) Failed to connect to 192.168.123.235 port 8080 after 0 ms: Connection refused`

From what I can tell, this seems to indicate that the server did not properly start. I also tried restarting the containers (`docker compose down` and `docker compose up`).

Any help is appreciated!

P.S. From what I've seen in the docs, the new app looks great!

### Local environment

**Version:**
v0.5.0

**docker-compose.yml:**
```
version: "3"
name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: server.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
      - "./certs:/certificates"
    ports:
      - "8080:8080"
      - "4040:3000"

  db:
    image: mysql:8.0
    restart: always
    env_file: server.env
    volumes:
      - "./db:/var/lib/mysql"

  cache:
    image: redis:7.2.1
    restart: always
```

**server.env:**
```
#
# DB
#
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_DATABASE=bootdb
MYSQL_ROOT_PASSWORD=root

#
# JWT
#
JWT_SECRET=secret
JWT_EXP=1

#
# Server config
#
USERS_LIMIT=-1
UPLOAD_DIR=/upload-dir
API_PORT=8080
TREFLE_KEY=key
LOG_LEVEL=DEBUG
ALLOWED_ORIGINS=*

#
# Cache
#
CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

#
# SSL
#
SSL_ENABLED=false
CERTIFICATE_PATH=/certificates/
```

**Logs:**
Output from ` docker container logs plant-it-server-1`
[plant-it-server-logs.txt](https://github.com/MDeLuise/plant-it/files/15213877/plant-it-server-logs.txt)
When looking through the logs, I found a few interesting lines (starts at line 1580):
`org.springframework.context.ApplicationContextException: Unable to start web server`
`Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat`
and several instances of `Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name ...`
