### ISSUE TITLE
MalformedJsonException when searching in Trefle db

### ISSUE THREAD

**Issue by astappiev** [MDeLuise/plant-it#229]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

After running the server I got the following error when I attempted to search for new plants (using Trefle)
```
{
    "statusCode": 500,
    "errorCode": "INTERNAL_SERVER_ERROR",
    "message": "com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $"
}
```
This error is found in browser logs on `/api/botanical-info` request. There is nothing that happens on the frontend.
Also, the server logs are clear, and nothing suspicious.

Of course, the configuration already includes ignoring certificates of Trefle.

### Local environment

Last server logs:
```
server-1  | 2024-06-29T20:38:11.719Z DEBUG 21 --- [nio-8080-exec-4] c.g.m.p.p.PlantInfoExtractorFacade       : Extract botanical info matching ros (size 5)
server-1  | 2024-06-29T20:38:11.720Z DEBUG 21 --- [nio-8080-exec-4] c.g.m.p.b.BotanicalInfoService           : Search for DB saved botanical info matching 'ros' scientific name (max size 5)
server-1  | 2024-06-29T20:38:11.731Z DEBUG 21 --- [nio-8080-exec-4] c.g.m.p.p.trafle.TrefleRequestMaker      : Fetching info for "ros" from Trefle
```

Docker compose
```
name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: server.env
    depends_on:
 #     - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
      - "./certs:/certificates"
    ports:
      - "8042:8080"
      - "8041:3000"
    extra_hosts:
      - "db:host-gateway"
#  db:
#    image: mysql:8.0
#    restart: always
#    env_file: server.env
#    volumes:
#      - "./db:/var/lib/mysql"

  cache:
    image: redis:latest
    restart: always
```
