### ISSUE TITLE
org.hibernate.AssertionFailure: force initializing collection loading

### ISSUE THREAD

**Issue by mavandeh** [MDeLuise/plant-it#314]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

Summary:
Occurs when adding another plant from the same Genus species. Both web app and android app display the error: `Error: Error while performing the operation`.

Docker plant-it-db-1 log:
```
2024-09-29T17:05:21.775Z ERROR 158 --- [nio-8080-exec-3] org.hibernate.AssertionFailure           : HHH000099: an assertion failure occurred (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session): org.hibernate.AssertionFailure: force initializing collection loading
```
Steps for reproducing:
- Server setup with floracodex
- Search for plant (eg. "Capsicum anuum") which already exists in your plants
- click "Add Plant"
- Error occurs

### Local environment

Docker compose running on a virtualized server.

docker-compose.yaml
```yaml
name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: server.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
      - "./certs:/certificates"
    ports:
      - "8081:8080"
      - "3001:3000"

  db:
    image: mysql:8.0
    restart: always
    env_file: server.env
    volumes:
      - "./db:/var/lib/mysql"

  cache:
    image: redis:7.2.1
    restart: always
```
    
server.env:
```sh
#
# DB
#
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=
MYSQL_PSW=
MYSQL_DATABASE=
MYSQL_ROOT_PASSWORD=

#
# JWT
#
JWT_SECRET=
JWT_EXP=1

#
# Server config
#
USERS_LIMIT=-1
UPLOAD_DIR=/upload-dir
API_PORT=8080
FLORACODEX_KEY=
LOG_LEVEL=DEBUG
ALLOWED_ORIGINS=*

#
# Cache
#
CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

```
