### ISSUE TITLE
Invalid API Key no matter what I use

### ISSUE THREAD

**Issue by Dvalin21** [MDeLuise/plant-it#336]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

Just as it say in the title. I look into the logs and it says that its using ForaCodex, but the moment I go to the frontend it say invalid API key. Not sure what could be causing this issue. 

```
JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
plant-it-server-1  | 2024-10-22T07:00:26.557Z DEBUG 26 --- [           main] c.g.m.p.p.PlantInfoExtractorFacade       : FloraCodex service used
plant-it-server-1  | 2024-10-22T07:00:27.171Z  INFO 26 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/api'
plant-it-server-1  | 2024-10-22T07:00:27.187Z  INFO 26 --- [           main] c.github.mdeluise.plantit.Application    : Started Application in
```

### Local environment

```
name: plant-it
services:
  server:
    image: msdeluise/plant-it-server:latest
    env_file: .env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - /home/incus/plantit/upload-dir:/upload-dir
      - /home/incus/docker/plantit/certs:/certificates
    ports:
      - 8881:8080
      - 3088:3000
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - /home/incus/plantit/db:/var/lib/mysql
  cache:
    image: redis:7.2.1
    restart: always
```
Env

```
#
# DB
#
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_ROOT_PASSWORD=password
MYSQL_DATABASE=plantit
MYSQL_PSW=password


# JWT
#
JWT_SECRET=Secret
JWT_EXP=1

#
# Server config
#
USERS_LIMIT=2                # less then 0 means no limit
UPLOAD_DIR=/upload-dir
API_PORT=8080
FLORACODEX_KEY="key"
UPDATE_EXISTING=true
ALLOWED_ORIGINS=*                # CORS allowed origins (comma separated list)
CONTACT_MAIL=email
LOG_LEVEL=DEBUG                  # could be: DEBUG, INFO, WARN, ERROR
REMINDER_NOTIFY_CHECK=0 30 7 * * * # 6-values crontab expression to set the check time for reminders
MAX_REQUESTS_PER_MINUTE=100 # rate limiting of the upcoming requests
GOTIFY_ENABLED=true

#
# SSL
#
SSL_ENABLED=true
CERTIFICATE_PATH=/certificates/ # path to files to use for ssl. If on docker deployment leave as it is and change the volume binding in the docker-compose file if needed

#
# Cache
#
CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

#
# SMTP
#
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTH=true
SMTP_START_TTL=true
SMTP_EMAIL=email
SMTP_PASSWORD="password"

```
