### ISSUE TITLE
[Docker] Cannot connect to the backend

### ISSUE THREAD

**Issue by tiritibambix** [MDeLuise/plant-it#60]
### Avoid duplicated bug reports

- [X] I've found a bug and checked that there are no open or closed bug report related to this.

### Description

Plant-it just won't work. I get the `Cannot connect to the backend` error.
Please, see my environment bellow.

### Expected behaviour

It should work, I'm following the instructions.

### Steps to reproduce

Edit docker-compose.yml, backend.env and frontend.env to your liking
Run docker compose up -d
Go to http://192.168.1.103:3009 (cf config bellow)
Can access the WebUI, but an error message is displayed.

### Local environment

Docker-compse.yml:
```
version: "3"

name: plant-it
services:
  backend:
    image: msdeluise/plant-it-backend:latest
    env_file: backend.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "/srv/Files/Plant-it/upload-dir:/upload-dir"
    ports:
      - "8089:8080"

  db:
    image: mysql:8.0
    restart: always
    env_file: backend.env
    volumes:
      - "/srv/Files/Plant-it/db:/var/lib/mysql"

  cache:
    image: redis:7.2.1
    restart: always

  frontend:
    image: msdeluise/plant-it-frontend:latest
    env_file: frontend.env
    links:
      - backend
    ports:
      - "3009:3000"
```

Frontend:
```
PORT=3009
API_URL=http://192.168.1.103:8089/api #ip of my machine with docker running plant-it
WAIT_TIMEOUT=5000

PAGE_SIZE=25

BROWSER=none
```

Backend:
```
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=bootdb

JWT_SECRET=32characterscomplicatedsecret
JWT_EXP=1

USERS_LIMIT=2 # including the admin account, so <= 0 if undefined, >= 2 if defined
UPLOAD_DIR=/upload-dir
API_PORT=8089

CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

TRAFLE_KEY=

ALLOWED_ORIGINS=*
```

**Comment by MDeLuise** [comment]
Hi @tiritibambix, thanks for opening the issue.

If you want to have the following setup:
* backend service on the `8089` port
* frontend service on the port `3009`

you should use the following files:

`docker-compose.yml`:
```
version: "3"

name: plant-it
services:
  backend:
    image: msdeluise/plant-it-backend:latest
    env_file: backend.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "/srv/Files/Plant-it/upload-dir:/upload-dir"
    ports:
      - "8089:8080"

  db:
    image: mysql:8.0
    restart: always
    env_file: backend.env
    volumes:
      - "/srv/Files/Plant-it/db:/var/lib/mysql"

  cache:
    image: redis:7.2.1
    restart: always

  frontend:
    image: msdeluise/plant-it-frontend:latest
    env_file: frontend.env
    links:
      - backend
    ports:
      - "3009:3000"
```

`frontend.env`:
```
PORT=3000
API_URL=http:///192.168.1.103:8089/api #ip of my machine with docker running plant-it
WAIT_TIMEOUT=5000

PAGE_SIZE=25

BROWSER=none
```

`backend.env`:
```
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_USERNAME=root
MYSQL_PSW=root
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=bootdb

JWT_SECRET=32characterscomplicatedsecret
JWT_EXP=1

USERS_LIMIT=2 # including the admin account, so <= 0 if undefined, >= 2 if defined
UPLOAD_DIR=/upload-dir
API_PORT=8080

CACHE_TTL=86400
CACHE_HOST=cache
CACHE_PORT=6379

TRAFLE_KEY=

ALLOWED_ORIGINS=*
```


In fact, on a docker compose deployment in order to change the port it needs to be change only the port binding in the `docker-compose` file.
The other way to change port (via variables `API_PORT` and  `PORT`) is used in a non docker deployment.
