### ISSUE TITLE
Support for linux/arm/v7 docker image for Raspberry Pi 4

### ISSUE THREAD

**Issue by BrunnerLivio** [MDeLuise/plant-it#64]
### Avoid duplicated feature requests

- [X] There are no open or closed feature requests that are related to this request

### Description

I would like to self-host plant-it on my Raspberry Pi 4. For that, I'd require a Docker image built for `linux/arm/v7`.

When running the following command on my Raspberry Pi 4:

```bash
docker pull msdeluise/plant-it-backend:latest
```

I get the following error:

```
no matching manifest for linux/arm/v7 in the manifest list entries
```

### Solution

- Build the docker image for `linux/arm/v7`
- Add an installation instruction for Raspberry Pi specifically (MySQL Docker image also doesn't support armv7 out of the box, maybe [this image works instead](https://hub.docker.com/r/beercan1989/arm-mysql/tags)?

**Comment by MDeLuise** [comment]
Hi @BrunnerLivio, thanks for the feedback!

I started to take a look at this issue, I pushed on DockerHub a version that should run on the raspberry pi of both the backend (`msdeluise/plant-it-backend:test-arm`) and the frontend (`msdeluise:plant-it-frontend:test`).

Right now I can not test the deployment on a raspberry pi, but I will as soon as possible.
If you want, you can test the following deployment and give me some feedback (remember to create a `backend.env` and a `frontend.env` file [as written here](https://github.com/MDeLuise/plant-it?tab=readme-ov-file#configuration)):
```
version: "3"

name: plant-it
services:
  backend:
    image: msdeluise/plant-it-backend:test-arm
    env_file: backend.env
    depends_on:
      - db
      - cache
    restart: unless-stopped
    volumes:
      - "./upload-dir:/upload-dir"
    ports:
      - "8080:8080"

  db:
    image: beercan1989/arm-mysql:5.7.33-1
    restart: always
    env_file: backend.env
    volumes:
      - "./db:/var/lib/mysql"

  cache:
    image: redis:7.2.1
    restart: always

  frontend:
    image: msdeluise/plant-it-frontend:latest
    env_file: frontend.env
    links:
      - backend
    ports:
      - "3000:3000"
```
